# kpa_health_ui/render.yaml
services:
  - type: web
    name: kpa-health-ui
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://kpa-health-api.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html